name: Build plugin

on:
  push:
    tags:
      - '*'

env:
  PLUGIN_NAME: logseq-sync-calendar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '19.x'
      - name: Build
        id: build
        run: |
          npm i && npm run build
          mkdir ${{ env.PLUGIN_NAME }}
          cp README.md package.json ${{ env.PLUGIN_NAME }}
          mv build ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
      - name: Upload zip file
        id: upload_zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
